### PR TITLE
feat(reporter): merge coverage results

### LINKED ISSUE #5: Support for uploading reports for multiple browsers
I don't really know how this should work yet! But it would be neat.

### PR DESCRIPTION
**Pull request by taion**
Closes #5

I don't have any configurability here because it seems like you'd always want to merge `lcov.info` files if multiple are present.

I had to update the text fixture to make `lcov-result-merger` happy.

### CODE REVIEW

**Comment by caitp** [comment]
it looks pretty good in general --- one thing that would be good is to actually test the merging behaviour, it looks like we're still only using one lcov.info in the test fixture. And maybe, this should be turned into a separate fixture to be tested seperately.

LGTM though.

**Comment by taion** [comment]
Regarding the merging behavior - we unconditionally pipe through the merge handler in all cases, and the merge handler itself already has test coverage that it works, so I thought it might not have been strictly necessary to add an explicit test (i.e. checking that the file made it through was enough).

Let me take a quick stab at seeing if I can set up a minimal fixture for this, though.

**Comment by taion** [comment]
I added the test case for the file merging.

It looked like there were a few bugs with how the other tests were set up, so I fixed those as well.

**Comment by taion** [comment]
One sec.

**Comment by taion** [comment]
This involved making more changes than I expected - more detail in the line notes.

**Comment by taion** [comment]
Crud, I blew away the line notes on accident when I updated the commit comment. Sorry.

**Comment by caitp** [comment]
Well it looks basically alright, I'm going to make sure it works still on the repos I know that use it before releasing, and it may need to be reverted if it can't quite work --- but it's probably fine. more test coverage is always good

**Comment by taion** [comment]
For comparison,

Before: https://coveralls.io/builds/4075549
After: https://coveralls.io/builds/4076870

For the repo on which I wanted this to work - had some code paths that were only triggered in specific browsers.

**Comment by taion** [comment]
Sorry again for the incorrect assertions about path handling.

Is this looking releasable in its current state?

**Comment by taion** [comment]
@caitp 

Actually, I'm starting to think this is a bad feature. Coveralls is happy enough to merge builds across multiple browsers/environments if you use a build matrix on Travis (or the equivalent). It looks like e.g. https://coveralls.io/builds/4290943.

What do you think of backing out this feature change (but keeping the updates to the tests)?

**Comment by caitp** [comment]
I'd rather you updated it to just be optional

**Comment by taion** [comment]
I definitely agree now that this behavior is a bad default. What's the benefit of allowing users to enable this behavior, though? It seems like the standard way to run a build matrix is to actually set up a matrix on Travis. Is there a benefit to explicitly merging coverage within a single task in this manner, rather than letting Coveralls take care of it?

**Comment by caitp** [comment]
Because you may not be using Travis, or may be running multiple suites in the same job, so the Travis matrix isn't always the solution

**Comment by taion** [comment]
In that case, do you think it might make more sense to only run results through the merging if there's more than one set of coverage results available?

**Pull request merged**
