### PR TITLE
Runs code coverage report in Travis. Adds coveralls badge.

### PR DESCRIPTION
**Pull request by yagoferrer**

### CODE REVIEW

**Comment by caitp** [comment]
if I'm not mistaken, the meat of this PR is 09de059...476739f is that right?

**Comment by yagoferrer** [comment]
Yes! My bad, I tried to merge everything in... but I failed.

**Comment by caitp** [comment]
try using `git pull --rebase origin master` next time, it's the one-liner I usually use

**Comment by yagoferrer** [comment]
ok good to know!

**Pull request closed without merging**
