### PR TITLE
Resolve file path from karma base path (rootConfig.basePath)

### PR DESCRIPTION
**Pull request by poying**
This is what [karma-coverage](https://github.com/karma-runner/karma-coverage) does.

### CODE REVIEW

**Comment by caitp** [comment]
you'll need to add `basePath` to the mock karma config in `rootConfig` --- or, to be a little more adventurous, use a real config object from karma, which should be easily doable

**Comment by caitp** [comment]
otherwise lgtm

**Comment by poying** [comment]
@caitp It seems much easier to modify the mock karma config then use real config object. :smirk:

**Comment by caitp** [comment]
it is easier, but using a real config object is probably more valuable, closer to an e2e test

**Comment by poying** [comment]
@caitp Ok let me try it.

**Comment by poying** [comment]
@caitp Is it ok with you?

**Comment by caitp** [comment]
I was thinking just like

```js
var Config = require('karma/lib/config').Config;

var config = new Config;
config.set({
  // the mock values
});
```

**Comment by poying** [comment]
I see.

**Comment by caitp** [comment]
looks good to me

**Comment by caitp** [comment]
thanks so much!

**Pull request closed without merging**
